### ISSUE TITLE
images

### ISSUE THREAD

**Issue by MichaelDimmitt** [LunchPools/LunchPool#10]
![lunchpools_square_icon_logo_sm](https://user-images.githubusercontent.com/11463275/48664322-e5584380-ea6a-11e8-81db-7282a2bc6636.png)

**Comment by MichaelDimmitt** [comment]
![lunchpools](https://user-images.githubusercontent.com/11463275/48664367-8fd06680-ea6b-11e8-9c91-d0a5ead90114.png)

**Comment by MichaelDimmitt** [comment]
![image](https://user-images.githubusercontent.com/11463275/48716809-25900100-ebe6-11e8-80d4-487cc880a142.png)

**Comment by MichaelDimmitt** [comment]
![image](https://user-images.githubusercontent.com/11463275/48716825-32acf000-ebe6-11e8-81d1-69c6a708773d.png)

**Comment by alex-abell** [comment]
![logo - red text](https://user-images.githubusercontent.com/7960991/48717575-b9160180-ebe7-11e8-9786-68980dab412f.png)
